### ISSUE TITLE
listen_mode setting interpreted wrong

### ISSUE THREAD

**Issue by fstr** [mayflower/puppet-php#111]
Hi,
for my setup I'm configuring the php5-fpm socket in my node's hiera config

```
php::fpm::pools:
  www:
    listen: /var/run/php5-fpm.sock
    listen_owner: www-data
    listen_group: www-data
    listen_mode: 0666
```

Since the listen_mode is a simple number there is no need to put it in quotes in your yaml configuration.
Sadly, Ruby will interpret this as an **octal** number (438), because of the leading 0. So the permissions of my php5-fpm.sock are completely off.

```
irb(main):002:0> 0666
=> 438
```

I didn't find any solution to this, because at the moment you have access to this config variable in Puppet it's already a Fixnum. And without knowing the original input, you can't know the base. Maybe you can read the original input and force it as a String?

Or Hiera should interpret all provided config variables as Strings? So I wouldn't call it an issue with this module per se, but you should at least consider it for your manual.

Users either have to provide:
```
listen_mode: '0666'
#listen_mode: '666'
```
or
```
listen_mode: 666
```
