### ISSUE TITLE
pecl reinstall package every puppet execution

### ISSUE THREAD

**Issue by stupied4ever** [mayflower/puppet-php#120]
Every execution puppet reinstalls the pecl modules (probably because the pecl upgrade). This is a big problem as it forces the fpm to reload (causing backend connection problem).

My hiera:
```yaml
php::extensions:
  apc:
    provider: pecl
  pdo_mysql:
    provider: pecl
```

Agent output:
```
Notice: /Stage[main]/Php/Php::Extension[pdo_mysql]/Package[pecl-pdo_mysql]/ensure: created
Notice: /Stage[main]/Php/Php::Extension[apc]/Package[pecl-apc]/ensure: created
```

Exist any workaround?
