### ISSUE TITLE
Custom repo ppa installing php-dev of different version.

### ISSUE THREAD

**Issue by reinaldomendes** [mayflower/puppet-php#186]
I'm using this ppa ondrej/php5-5.6

```
php::repo::ubuntu::ppa: 'ondrej/php5-5.6'
php-dev: true
php::extensions:
 lzf:
    provider: pecl
    header_packages:
    - build-essential
    - php-pear

```

php-dev version - 20121212
php version 20131226

To fix this problem I need to exec 
```bash
apt-get purge php5-dev 
pecl uninstall lzf
apt-get install php5-dev 
pecl install lzf
```
