### ISSUE TITLE
Invalid relationship: Php::Config[opcache] { require => Package[undef] }

### ISSUE THREAD

**Issue by brentclark** [mayflower/puppet-php#228]
Good day

I get the following, for Im trying to manage opcache settings (Opcache is part and parcel of PHP 5.6 and is not a package).

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Php::Config[opcache] { require => Package[undef] }, because Package[undef] doesn't seem to be in the catalog

Here is my hiera details.
```
php::extensions:
  opcache:
    provider: 'none' # There is no php-opcache package.
    settings:
      opcache.revalidate_freq: 7200
.... snippet
      opcache.force_restart_timeout: 30
      opcache.enable: 1
```
I find if I comment out line:
```diff
diff --git a/manifests/extension.pp b/manifests/extension.pp
index 0f2fd46..391e9e0 100644
--- a/manifests/extension.pp
+++ b/manifests/extension.pp
@@ -186,7 +186,7 @@ define php::extension(
   ::php::config { $title:
     file    => "${config_root_ini}/${lowercase_title}.ini",
     config  => $final_settings,
-    require => Package[$real_package],
+    #require => Package[$real_package],
   }
```
Ubuntu/Debian systems use the mods-available folder. We need to enable

This works.

HTH
Brent
