### ISSUE TITLE
Ensure extension settings prefix

### ISSUE THREAD

**Issue by mbrodala** [mayflower/puppet-php#81]
Currently extension settings have to specified like this:

```yaml
php::extensions:
  apc:
    package_prefix: php-
    settings:
      apc.stat: 1
      apc.stat_ctime: 1
```

A bit more intuitive and de-duplicating would be this:

```yaml
php::extensions:
  apc:
    package_prefix: php-
    settings:
      stat: 1
      stat_ctime: 1
```

To provide the still-required extension prefix, the [`prefix()`](https://github.com/puppetlabs/puppetlabs-stdlib#prefix) function from `puppetlabs-stdlib` could be used but in that case existing configuration would lead to something like `apc.apc.stat` and break. Thus a separate function could be necessary to only add the prefix if not present.

Any opinions if this is worth adding?
